### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by ThomWright** [seckwei/SirKit_CircuitSim#1]
I like how you're documenting your questions and solutions as you go. It's a great idea!

When I had more free time I started writing down some stuff in a [gitbook](https://www.gitbook.com/book/thomwright/electronic-circuit-simulation/details). It's very rough and needs a load more time to make it useful to anyone.

I learned what I know about circuit simulation by working on Falstad's source code, and reading [Electronic Circuit and System Simulation Methods](https://www.amazon.co.uk/Electronic-Circuit-System-Simulation-Methods/dp/0071347704/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=). There are currently some decently priced paperbacks on Amazon for the first time I've seen.

If you're interested in collaborating, or have any questions, do get in touch. I have an email on my profile :)

Good luck with the project

**Comment by seckwei** [comment]
Thank you very much! :smile:

I was looking for an alternative for posting my documentations and gitbook might be ideal. Didn't realise that you have a documentation for the circuit-sim as it's not linked in the project, but I'll definitely have a look through it.

I have had a quick look into Falstad's source code from Iain Sharp's port to JS as well but couldn't get my head around the inner workings that much yet. Currently, I am just "living" off Google and a few other websites linked in my documentation, so your reading suggestions and recommendations are very much appreciated.

Not sure how far I'll drive this project, but it is pretty addictive to develop it!
Will get in touch if there's an opportunity for collab :+1: Do drop me an email as well if there's anything you'd like to know more about this project (just realised I hid my email from my profile, but it is there now).

Thanks again!
